### ISSUE TITLE
Incorrect instructions for deploying logger

### ISSUE THREAD

**Issue by jlack1987** [ihmcrobotics/ihmc-open-robotics-software#104]
In going through the instructions for locally deploying the logger I think I have found some of the documentation [here](https://github.com/ihmcrobotics/ihmc-logger-docker) to be incorrect. 

The instructions say to navigate to the `RobotDataCommunication` directory then run the command to build the logger. For me I had to run the script from the root directory of `IHMCOpenRoboticsSoftware` and the resulting `.tar` file was dumped to `IHMCOpenRoboticsSoftware/IHMCRobotDataLogger/build/distributions` and the documentation says it'll be at `RobotDataCommunication/build/distributions`.

**Comment by dljsjr** [comment]
Cool, thanks. RobotDataCommunication got split up recently in to two separate projects for logging and visualizing and this doc got missed in the refactor. This'll be addressed shortly.
