### ISSUE TITLE
whole_body_trajectory message with two trajectory points close together in time blows up the controller

### ISSUE THREAD

**Issue by dljsjr** [ihmcrobotics/ihmc-open-robotics-software#11]
Originally reported by: **Vladimir Ivan (Bitbucket: [vivan](http://bitbucket.org/vivan), GitHub: [vivan](http://github.com/vivan))**

----------------------------------------

When a whole_body_trajectory contains two trajectory points close in time (<0.2s), the jumps or even blows up (in the simulation).

This behaviour can be reproduced in the simulator:
 1. Run ```ValkyrieROSSimulator.java```
 2. Publish the control message from the attached ROS bag file.

The smaller the time between the two trajectory points, the bigger the effect.

----------------------------------------
- Bitbucket: https://bitbucket.org/ihmcrobotics/ihmc-open-robotics-software/issue/7

**Comment by SylvainBertrand** [comment]
With the new controller, you'll be able to either request the controller to start directly from the first trajectory point (if its time == 0.0), or request the controller to prepend a trajectory point at its current desired (if time > 0.0). Using the second option, you will still obtain weird behaviors if the time to reach the first trajectory point is small and it is far from the current desired in terms of position/orientation.
