### ISSUE TITLE
Exported Video From SCS Plays Back At Correct Rate

### ISSUE THREAD

**Issue by calvertdw** [ihmcrobotics/ihmc-open-robotics-software#111]
30 fps export is around 6% faster than realtime.
60 fps video is closer to 15% faster.
Expect some integer rounding error or something.

**Comment by dljsjr** [comment]
This is definitely still an issue.

**Comment by vkrm1612** [comment]
Can I fix this issue......!

**Comment by calvertdw** [comment]
Hi @vkrm1612! Sure, if you want to submit a PR I'd be happy to look at it. Also, if you need any help just let me know.
