### ISSUE TITLE
GitHub Releases are cleaned up

### ISSUE THREAD

**Issue by dljsjr** [ihmcrobotics/ihmc-open-robotics-software#112]
Right now the GitHub Releases page for this repo is pretty noisy; this is actually a side effect of us not actually making releases and just having release placeholders for all of our tags showing up.

As far as I can tell you can't actually turn off the auto-creation of placeholders for tags, but we should start making "actual" releases of the software on GitHub. This requires the attachment of a binary, so I'm not sure what that should be; possibly a tarball of all the .jars for every project in the repo?

Soliciting input from whoever is interested. Particularly @calvertdw @nmertins

**Comment by calvertdw** [comment]
We have made a proper GitHub release for https://github.com/ihmcrobotics/ihmc-open-robotics-software/releases/tag/0.11.0 and GItHub actually provides tarballs by default, so I think this issue is resolved. @dljsjr I will close this, but can reopen if needed.
