### ISSUE TITLE
Hybrid taskspace-jointspace messages are not built correctly

### ISSUE THREAD

**Issue by wxmerkt** [ihmcrobotics/ihmc-open-robotics-software#139]
| Required Info | |
|---|---|
|Version or commit hash|release/0.10.0|

#### Steps to reproduce issue
Have a look at https://github.com/ihmcrobotics/ihmc_ros_core/blob/release/0.10.0/ihmc_msgs/msg/HandHybridJointspaceTaskspaceTrajectoryRosMessage.msg - the message contains neither joint nor task space components. The only hybrid message to do so is ``Chest``.

#### Contributors with relevant knowledge or expertise (optional)
@dljsjr

**Comment by dljsjr** [comment]
Hey @wxmerkt!

Thanks for the report. This is fixed in the upcoming 0.12 release, but it probably won't be back ported to 0.10.

**Comment by dljsjr** [comment]
This is the release that switches to ROS 2 and leverages the ROS 1 Bridge package for folks that still need to use ROS 1. I'm in Houston this week testing on their robot to make sure that we have the packaging and ansible playbooks sorted out then we'll be doing acceptance tests on our robot in Pensacola when I get back. We don't have a hard ETA on 0.12 but we're aiming to have it out this summer. It's a pretty large release with a lot of changes under the hood so we want to make sure it's well tested.

**Comment by wxmerkt** [comment]
Okay, we are happy to switch once it's well tested.
