### ISSUE TITLE
Documentation feature: node_modules folder is huge

### ISSUE THREAD

**Issue by calvertdw** [ihmcrobotics/ihmc-open-robotics-software#140]
The [node_modules](https://github.com/ihmcrobotics/ihmc-open-robotics-software/tree/develop/websitedocs/website/node_modules) folder is around 50MB and contains 12,758 files and has no relation to IHMC code. This should not be on develop.

@dljsjr @SylvainBertrand leaving this here so we don't forget

**Comment by dljsjr** [comment]
These get generated by the yarn/npm bootstrapping process and shouldn't be versioned, we definitely need to remove them. The package.json and package-lock.json are enough information for yarn/npm to redownload these modules on demand.

**Comment by dljsjr** [comment]
We'll also have to probably comb over the repo w/ BFG once we've cleaned everything up so they're not in history anymore.

**Comment by calvertdw** [comment]
This has been fixed.
