### ISSUE TITLE
Footstep planner can step on own feet with Valkyrie

### ISSUE THREAD

**Issue by calvertdw** [ihmcrobotics/ihmc-open-robotics-software#146]

**Comment by stevenjj** [comment]
Hey Stephen,
This only happens on the real robot and in gazebo. In SCS, it doesn't show up. Are there parameters we can change to take less conservative steps or increase foot distance with the planner?

**Comment by stevenjj** [comment]
Also, the footstep plans themselves look ok. It's during execution that she sometimes steps on her feet. These are particularly evident on consecutive footsteps that have some yaw angle differences

**Comment by stephenmcc** [comment]
Gotcha. If the footstep plan looks good then it is a problem with the controller - either the swing foot has bad tracking or the controller is adjusting the footstep too much. Would it be possible to get a log of this happening on the real robot?

**Comment by stevenjj** [comment]
That makes sense. 
Alright, sure thing. We're about to get the robot walking again after some CoP offset changes, so we'll send you logs when we can walk.  Thanks for being prompt about this.
