### ISSUE TITLE
Question: Control position of joint in simulation

### ISSUE THREAD

**Issue by alextac98** [ihmcrobotics/ihmc-open-robotics-software#153]
| Required Info | |
|---|---|
|n/a||
|Simulation||
|Ubuntu 16.04||
|JDK||

Is there any way to set the position of a joint without dealing with torque and PID in simulation? I was able to figure out how to move a joint and link around using torque, but I specifically want to just worry about the position of a certain leg, as the PIDs are dealt with locally on my motors.

#### Steps to reproduce issue

N/A

#### Expected behavior

N/A
#### Actual behavior

N/A
#### Contributors with relevant knowledge or expertise (optional)

N/A

**Comment by dljsjr** [comment]
Hey @alextac98,

Unfortunately no, there is no API for doing position control directly on the joints. There are setters for `q` on the joint which is the generalized position coordinate but if the joint has dynamics enabled then as the simulator runs the physics loop will move the joint away from where you set it. This is just a result of the physics engine constantly computing the forces being expressed.

The easiest way to do a position controlled joint, as you've mentioned, is to use a PID loop that works on position error and outputs joint torques. You don't need to model the PID loop of your motor for this, you can just use one under the hood and treat it as a position control API.  We have built-in PID control objects in our simulation libraries that you can use. The `PIDController` class provides a pretty standard PID implementation that you can use for this.
