### ISSUE TITLE
IHMC Log Files should log stdout/stderr

### ISSUE THREAD

**Issue by dljsjr** [ihmcrobotics/ihmc-open-robotics-software#16]
IHMCLogger should log stdout/stderr so we can get at output from runs when robots are not being managed using IHMC Mission Control (currently, the only robot managed by IHMC Mission Control is Atlas).

There is an internal JIRA ticket on the IHMC JIRA for this, but as JIRA isn't public yet and we don't have a nice way of bridging our JIRA with GitHub Issues I wanted to make this issue as well.

IHMC JIRA key is ROSI-381.

**Comment by dljsjr** [comment]
Test comment, please ignore.

**Comment by dljsjr** [comment]
I'd still like to see this. I'm making a maintenance/feature improvement pass on the logger soon.

**Comment by calvertdw** [comment]
The new log-tools library might help: https://github.com/ihmcrobotics/log-tools
