### ISSUE TITLE
Releases are no longer available on Bintray

### ISSUE THREAD

**Issue by StephenWelch** [ihmcrobotics/ihmc-open-robotics-software#190]
| Required Info | |
|---|---|
|Version or commit hash|N/A|
|Sim or Real Robot|N/A|
|Operating System|N/A|
|JDK|N/A|

#### Steps to reproduce issue
Attempt to access Bintray-hosted Maven repo linked in README

#### Expected behavior
Maven repo can be successfully accessed

#### Actual behavior
Bintray link is dead - Bintray was sunset May 1st, 2021

**Comment by calvertdw** [comment]
I believe this is fixed since we migrated to Maven Central.
