### ISSUE TITLE
Remove yaw drift

### ISSUE THREAD

**Issue by mauricefallon** [ihmcrobotics/ihmc-open-robotics-software#21]
We have now removed the imu with the magnetometers and are back using the original version (model 15). The orientation is now stable and we have the state estimation performance we saw in training. Happy days!

That still includes a 1-2 degree yaw bias per minute, which we really want to remove. I see some ihmc code modules that do bias estimation:
1. does this module work? I remember Peter talking about this for Atlas
2. it is enabled or can we enable it?
3. if no to 1 and 2 can we feed back a bias estimate (rather than just the position correction) to your state estimator?

**Comment by mauricefallon** [comment]
PS: We can estimate bias with our own estimator by learning it when standing still (at any time during the runs)

**Comment by mauricefallon** [comment]
Vielen Danke, has it been tested on the/any robot?

Does imuDriftYawRateFiltered hold the bias estimate? I guess I'm looking for a value of the order of 0.0003 rad/sec (about 1 deg/minute)

**Comment by SylvainBertrand** [comment]
estimatedIMUDriftYawRateFiltered does hold the bias estimate.
isIMUDriftYawRateEstimated => lets you know if the drift is currently being estimated
isIMUDriftCompensationActivated => lets you know if the bias is being removed from the IMU measurement.

**Comment by mauricefallon** [comment]
Just checked this and it works just fine. Thanks @SylvainBertrand 

The Bias estimated is about 0.001 rad/sec
I might suggest that the estimated bias drifts a little too much i.e. the alpha gain is too hight. And that it shouldn't be updated when walking. But I'll study more later.
