### ISSUE TITLE
Valkyrie feet contact points are evaluated.

### ISSUE THREAD

**Issue by mauricefallon** [ihmcrobotics/ihmc-open-robotics-software#58]
I'm wondering if the contact points for valkyrie's feet have changed - or possibly the urdf containing them? I notice the contact points are not at the corners of the feet, they are now a few cm further forward. Is this intentional?

This is what they look like:
![val_contact_points](https://cloud.githubusercontent.com/assets/6404227/16833887/30cbf542-49a9-11e6-8bf7-97030a5798c9.png)

And Atlas for comparison has them right at the back of the feet:
![atlas_contact_points](https://cloud.githubusercontent.com/assets/6404227/16833886/2f390080-49a9-11e6-98cf-95050b6bbc14.png)

FYI: @jlack1987 @dljsjr

**Comment by jlack1987** [comment]
I'm not sure if they have changed. I'm 99% sure those come from somewhere in SCS.

**Comment by SylvainBertrand** [comment]
I just compared with the contact points from January and they haven't changed.
I agree that they look a bit too conservative on the heels.
We usually refine those by running a few tests on the actual robot which we shipped back to NASA unfortunately. Let me see what I can do.

**Comment by dljsjr** [comment]
Updating this to remind myself that it still exists. This needs to be evaluated next time we have access to the physical robot.
