### ISSUE TITLE
SCS Simulation ROS Communication broken in develop

### ISSUE THREAD

**Issue by wxmerkt** [ihmcrobotics/ihmc-open-robotics-software#66]
Using ``new-api-beta3`` works with the ``ROS_IP`` and ``ROS_MASTER_URI`` work-around we've discovered back in June. The current head of develop does not publish ROS communication though - echoing joint_states is empty. Set-up is the same, checking out ``new-api-beta3`` and running it shows traffic, ``develop`` doesnt

cc @simalpha

**Comment by dljsjr** [comment]
@wxmerkt @simalpha Can you post the console output of all related IHMC processes? Stdout, err, exceptions, etc.

**Comment by dljsjr** [comment]
From a clean clone of IHMCOpenRoboticsSoftware, on `develop` (longform hash: 7a80a22aa0f19eed0d1d092466dd828f0526019e), running `ValkyrieRosAPISimulator.java`, I am not able to reproduce; I can echo `/ihmc_ros/valkyrie/output/joint_states` without issue and I can send commands to the simulator via the ROS endpoints.

**Comment by dljsjr** [comment]
I am unfortunately also unable to reproduce this issue using the `OpenHumanoidsSimulator.java` entry point.

**Comment by wxmerkt** [comment]
Cannot reproduce with anymore with ``new-api-beta4``, closing
