### ISSUE TITLE
Streaming head orientation messages blocks controller

### ISSUE THREAD

**Issue by dljsjr** [ihmcrobotics/ihmc-open-robotics-software#8]
Originally reported by: **Maurice Fallon (Bitbucket: [mauricefallon](http://bitbucket.org/mauricefallon), GitHub: [mauricefallon](http://github.com/mauricefallon))**

----------------------------------------

I observed that if HeadOrientationPacketMessage is streamed (e.g. 100Hz) to simulated Valkyrie in SCS, that the head doesn't move at all.

(The idea is that the camera is tracking something and streams HeadOrientationPacketMessage messages, causing the head to look at the target.)

I guess that the new messages over write the gains of the controller?

Sending a single individual command (and then stopping) is fine.

----------------------------------------
- Bitbucket: https://bitbucket.org/ihmcrobotics/ihmc-open-robotics-software/issue/4

**Comment by SylvainBertrand** [comment]
With the new controller, you'll be able to either request the controller to start directly from the first trajectory point (if its time == 0.0), or request the controller to prepend a trajectory point at its current desired (if time > 0.0).
So by sending a series of HeadTrajectoryMessage (the new message equivalent to HeadOrientationPacket) each composed of only one trajectory point with a time == 0.0, you'll be able to do streaming.
