### ISSUE TITLE
RobotDescription can be generated by reading a URDF

### ISSUE THREAD

**Issue by dljsjr** [ihmcrobotics/ihmc-open-robotics-software#81]

**Comment by dljsjr** [comment]
Just updating this, parsing the core of URDF is pretty straight forward but parsing the `<gazebo></gazebo>` extensions is proving to be a little difficult because of the way that the OSRF allows for those tags to contain arbitrary XML that just gets inlined when converting to SDF. Because we're not converting to SDF but actually trying to parse and construct a sim-ready model with sensors from these model descriptions, it's tricky to get JAXB's model of how XML should be formatted with this really weird edge case in URDF.

Solvable, just going to take a while.

**Comment by dljsjr** [comment]
Parsing the Gazebo extensions is now (seemingly) fixed in the above referenced commit (fe63e48). Work can resume on generating RobotDescription from URDF.

**Comment by calvertdw** [comment]
Done with URDFTools in SCS 2.
