### ISSUE TITLE
Log Visualizer does not work when logged data has no corresponding robot model

### ISSUE THREAD

**Issue by dljsjr** [ihmcrobotics/ihmc-open-robotics-software#95]
| Required Info |  |
| --- | --- |
| Version or commit hash | 0.8.0 |
| Sim or Real Robot | Both |
| Operating System | All |
| JDK | Any |

If a YoVariableServer is created with a `null` **`LogModelProvider`** but **`LogSettings.log`** is set to `true`, the logged data cannot be opened for offline analysis using **`LogVisualizer`**.
#### Steps to reproduce issue

Start an IHMC Logger either from source or using the latest release. Then start an arbitrary controller whose YoVariableServer has a null LogModelProvider constructor argument but LogSettings have log set to true. Run the control session for a while, then terminate the control session. Wait for the logger to finalize the logged data. Launch LogVisualizer, and open the log for the above session.
#### Expected behavior

The log should load with no robot model in the 3D Viewport.
#### Actual behavior

A popup appears saying that no robot model can be auto-detected, and that you must manually specify a robot model to use. Selecting any robot model or selecting cancel will all result in the visualizer throwing an exception and failing to start.

**Comment by jespersmith** [comment]
This issue is fixed in commit 02d379a on develop.
